apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-molm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iapl-tenant/rhtap-demo-app/hacbs-test-project-molm@sha256:86ced7d4d40837c7bb5438f93e445dc6c98ee599163de0408e2e1232a3518856
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
