apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-molm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iapl-tenant/rhtap-demo-app/hacbs-test-project-molm@sha256:210e4d1777adac96b7948432c95fe02b599008636cea40afc5b1b6f441ba9d45
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
