apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-molm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-molm
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-molm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-molm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-molm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iapl-tenant/rhtap-demo-app/hacbs-test-project-molm@sha256:210e4d1777adac96b7948432c95fe02b599008636cea40afc5b1b6f441ba9d45
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
